RestaurantManagement/Models/ResetPasswordViewModel.cs
using System;

namespace RestaurantManagement.Models
{
    public class ResetPasswordViewModel
    {
        public string NewPassword { get; set; }
        public string ConfirmNewPassword { get; set; }
    }
}

RestaurantManagement/Controllers/ResetPasswordController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using RestaurantManagement.Services;
using System;
using RestaurantManagement.Models;

namespace RestaurantManagement.Controllers
{
    public class ResetPasswordController : Controller
    {
        private readonly IResetPasswordService _resetPaswordService;

        public ResetPasswordController(IResetPasswordService resetPasswordService)
        {
            _resetPaswordService = resetPasswordService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index([FromForm]string username)
        {
            var success = await _resetPaswordService.SendMailResetPasswordAsync(username);
            return RedirectToAction(nameof(SendMailResetPasswordSuccess));
        }

        [HttpGet("/ResetPasswordHandle/{customerId}")]
        public IActionResult ResetPasswordHandle([FromRoute]Guid customerId)
        {
            return View(customerId);
        }

        [HttpPost("/ResetPasswordHandle/{customerId}")]
        public async Task<IActionResult> ResetPasswordHandle([FromRoute] Guid customerId, [FromForm] ResetPasswordViewModel resetPasswordViewModel)
        {
            var success = await _resetPaswordService.ResetPasswordAsync(customerId, resetPasswordViewModel);
            if (success)
            {
                return RedirectToAction(nameof(ResetPasswordSuccess));
            }
            return View(customerId);
        }

        public IActionResult ResetPasswordSuccess()
        {
            return View();
        }

        public IActionResult SendMailResetPasswordSuccess()
        {
            return View();
        }
    }
}

RestaurantManagement/Views/ResetPassword/Index.cshtml
@{
    Layout = null;
}
@model RestaurantManagement.Models.RegisterViewModel


<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
      rel="stylesheet"
      id="bootstrap-css" />
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>
    <title> Lấy lại mật khẩu </title>
    <!--Made with love by Mutiullah Samim -->
    <!--Bootsrap 4 CDN-->
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous" />

    <!--Fontawesome CDN-->
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
          integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
          crossorigin="anonymous" />

    <!--Custom styles-->
    <link rel="stylesheet" type="text/css" href="/css/site.css" />
</head>
<body class="login-page">
    <div class="container">
        <div class="d-flex justify-content-center h-100">
            <div class="card">
                <div class="card-header">
                    <h3>Quên mật khẩu</h3>
                </div>
                <div class="card-body">
                    <form asp-controller="ResetPassword" asp-action="Index" method="post">
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fas fa-user"></i>
                                </span>
                            </div>
                            <input type="text"
                                   class="form-control"
                                   placeholder="Tên tài khoản... "
                                   name="username" />
                        </div>
                        <div class="form-group">
                            <input type="submit"
                                   value="Khôi phục mật khẩu"
                                   class="btn float-right login_btn" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

RestaurantManagement/Views/ResetPassword/ResetPasswordHandle.cshtml
@{
    Layout = null;
}
@model System.Guid


<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
      rel="stylesheet"
      id="bootstrap-css" />
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>
    <title>Khôi phục mật khẩu</title>
    <!--Made with love by Mutiullah Samim -->
    <!--Bootsrap 4 CDN-->
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous" />

    <!--Fontawesome CDN-->
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
          integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
          crossorigin="anonymous" />

    <!--Custom styles-->
    <link rel="stylesheet" type="text/css" href="/css/site.css" />
</head>
<body class="login-page">
    <div class="container">
        <div class="d-flex justify-content-center h-100">
            <div class="card">
                <div class="card-header">
                    <h3>Khôi phục mật khẩu</h3>
                </div>
                <div class="card-body">
                    <form asp-controller="ResetPassword" asp-action="ResetPasswordHandle" method="post">
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fas fa-key"></i>
                                </span>
                            </div>
                            <input type="password"
                                   class="form-control"
                                   placeholder="Mật khẩu mới... "
                                   name="resetPasswordViewModel.NewPassword" />
                        </div>
                        <div class="input-group form-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fas fa-key"></i>
                                </span>
                            </div>
                            <input type="password"
                                   class="form-control"
                                   placeholder="Nhập lại mật khẩu mới... "
                                   name="resetPasswordViewModel.ConfirmNewPassword" />
                        </div> 
                        <div class="form-group">
                            <input type="submit"
                                   value="Khôi phục mật khẩu"
                                   class="btn float-right login_btn" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

RestaurantManagement/Views/ResetPassword/ResetPasswordSuccess.cshtml
@{ Layout = null; }
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="x-apple-disable-message-reformatting" />
        <title></title>
        <style>
            table,
            td,
            div,
            h1,
            p {
                font-family: Arial, sans-serif;
            }
        </style>
    </head>
    <body style="margin: 0; padding: 0">
        <div
            style="
                position: absolute;
                top: 50%;
                left: 50%;
                transform: translate(-50%, -50%);
            "
        >
            <table
                role="presentation"
                style="
                    width: 100%;
                    border-collapse: collapse;
                    border: 0;
                    border-spacing: 0;
                    background: #ffffff;
                "
            >
                <tr>
                    <td align="center" style="padding: 0">
                        <table
                            role="presentation"
                            style="
                                width: 602px;
                                border-collapse: collapse;
                                border: 1px solid #cccccc;
                                border-spacing: 0;
                                text-align: left;
                            "
                        >
                            <tr>
                                <td
                                    align="center"
                                    style="
                                        padding: 40px 0 30px 0;
                                        background: #70bbd9;
                                    "
                                >
                                    <img
                                        src="https://vm247.net/wp-content/uploads/2021/02/5-of-the-best-password-reset-emails.png"
                                        alt=""
                                        width="300"
                                        style="height: auto; display: block"
                                    />
                                </td>
                            </tr>
                            <tr>
                                <td style="padding: 36px 30px 42px 30px">
                                    <table
                                        role="presentation"
                                        style="
                                            width: 100%;
                                            border-collapse: collapse;
                                            border: 0;
                                            border-spacing: 0;
                                        "
                                    >
                                        <tr>
                                            <td style="color: #153643">
                                                <h1
                                                    style="
                                                        font-size: 24px;
                                                        margin: 0 0 20px 0;
                                                        font-family: Arial,
                                                            sans-serif;
                                                    "
                                                >
                                                    Thay đổi mật khẩu thành công
                                                </h1>
                                                <p
                                                    style="
                                                        font-size: 16px;
                                                        line-height: 24px;
                                                        font-family: Arial,
                                                            sans-serif;
                                                    "
                                                >
                                                    Hãy quay lại trang đăng nhập
                                                    và dùng mật khẩu mới!
                                                </p>
                                                <p
                                                    style="
                                                        margin: 0 20%;
                                                        line-height: 24px;
                                                    "
                                                >
                                                    <a
                                                        href="/Login"
                                                        style="
                                                            font: bold 20px
                                                                Arial;
                                                            text-decoration: none;
                                                            background-color: #ee4c50;
                                                            color: #fff;
                                                            padding: 15px;
                                                            display: block;
                                                            text-align: center;
                                                        "
                                                        >QUAY VỀ TRANG ĐĂNG
                                                        NHẬP</a
                                                    >
                                                </p>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding: 30px; background: #ee4c50">
                                    <table
                                        role="presentation"
                                        style="
                                            width: 100%;
                                            border-collapse: collapse;
                                            border: 0;
                                            border-spacing: 0;
                                            font-size: 9px;
                                            font-family: Arial, sans-serif;
                                        "
                                    >
                                        <tr>
                                            <td
                                                style="padding: 0; width: 100%"
                                                align="center"
                                            >
                                                <p
                                                    style="
                                                        margin: 0;
                                                        font-size: 14px;
                                                        line-height: 16px;
                                                        font-family: Arial,
                                                            sans-serif;
                                                        color: #ffffff;
                                                    "
                                                >
                                                    &reg; Restaurant, Việt Nam
                                                    2021<br />
                                                </p>
                                            </td>
                                            <td
                                                style="padding: 0; width: 50%"
                                                align="right"
                                            >
                                                <table
                                                    role="presentation"
                                                    style="
                                                        border-collapse: collapse;
                                                        border: 0;
                                                        border-spacing: 0;
                                                    "
                                                ></table>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </div>
    </body>
</html>

RestaurantManagement/Views/ResetPassword/SendMailResetPasswordSuccess.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="x-apple-disable-message-reformatting" />
        <title></title>
        <style>
            table,
            td,
            div,
            h1,
            p {
                font-family: Arial, sans-serif;
            }
        </style>
    </head>
    <body style="margin: 0; padding: 0">
        <div
            style="
                position: absolute;
                top: 50%;
                left: 50%;
                transform: translate(-50%, -50%);
            "
        >
            <table
                role="presentation"
                style="
                    width: 100%;
                    border-collapse: collapse;
                    border: 0;
                    border-spacing: 0;
                    background: #ffffff;
                "
            >
                <tr>
                    <td align="center" style="padding: 0">
                        <table
                            role="presentation"
                            style="
                                width: 602px;
                                border-collapse: collapse;
                                border: 1px solid #cccccc;
                                border-spacing: 0;
                                text-align: left;
                            "
                        >
                            <tr>
                                <td
                                    align="center"
                                    style="
                                        padding: 40px 0 30px 0;
                                        background: #70bbd9;
                                    "
                                >
                                    <img
                                        src="https://vm247.net/wp-content/uploads/2021/02/5-of-the-best-password-reset-emails.png"
                                        alt=""
                                        width="300"
                                        style="height: auto; display: block"
                                    />
                                </td>
                            </tr>
                            <tr>
                                <td style="padding: 36px 30px 42px 30px">
                                    <table
                                        role="presentation"
                                        style="
                                            width: 100%;
                                            border-collapse: collapse;
                                            border: 0;
                                            border-spacing: 0;
                                        "
                                    >
                                        <tr>
                                            <td style="color: #153643">
                                                <h1
                                                    style="
                                                        font-size: 24px;
                                                        margin: 0 0 20px 0;
                                                        font-family: Arial,
                                                            sans-serif;
                                                    "
                                                >
                                                    Gửi mail thành công
                                                </h1>
                                                <p
                                                    style="
                                                        margin: 0 0 12px 0;
                                                        font-size: 16px;
                                                        line-height: 24px;
                                                        font-family: Arial,
                                                            sans-serif;
                                                    "
                                                >
                                                    Đã gửi mail yêu cầu thay đổi
                                                    mật khẩu tới tài khoản của
                                                    bạn.
                                                </p>
                                                <p
                                                    style="
                                                        margin: 0 0 12px 0;
                                                        font-size: 16px;
                                                        line-height: 24px;
                                                        font-family: Arial,
                                                            sans-serif;
                                                    "
                                                >
                                                    Vui lòng kiểm tra hộp thư
                                                    điện tử của bạn và làm theo
                                                    hướng dẫn để thay đổi mật
                                                    khẩu mới.
                                                </p>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding: 30px; background: #ee4c50">
                                    <table
                                        role="presentation"
                                        style="
                                            width: 100%;
                                            border-collapse: collapse;
                                            border: 0;
                                            border-spacing: 0;
                                            font-size: 9px;
                                            font-family: Arial, sans-serif;
                                        "
                                    >
                                        <tr>
                                            <td
                                                style="padding: 0; width: 100%"
                                                align="center"
                                            >
                                                <p
                                                    style="
                                                        margin: 0;
                                                        font-size: 14px;
                                                        line-height: 16px;
                                                        font-family: Arial,
                                                            sans-serif;
                                                        color: #ffffff;
                                                    "
                                                >
                                                    &reg; Restaurant, Việt Nam
                                                    2021<br />
                                                </p>
                                            </td>
                                            <td
                                                style="padding: 0; width: 50%"
                                                align="right"
                                            >
                                                <table
                                                    role="presentation"
                                                    style="
                                                        border-collapse: collapse;
                                                        border: 0;
                                                        border-spacing: 0;
                                                    "
                                                ></table>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </div>
    </body>
</html>